### ISSUE TITLE
cURL error 18: transfer closed with 97 bytes remaining to read

### ISSUE THREAD

**Issue by mpjraaij** [s-ichikawa/laravel-sendgrid-driver#109]
The package is causing above error to happen and originates in SendGridTransport.php

Has anyone experience this as well? If so, how did you solve it?

**Comment by s-ichikawa** [comment]
I have not got this case. 
But maybe the cause is wrong `Content-Length` header?
https://stackoverflow.com/a/1761718

**Comment by rognales** [comment]
I have not set any headers but still getting the error

**Comment by skeeith** [comment]
Have anyone know how to fix this? I am having this issue right now on my sendgrid

**Comment by JorisDebonnet** [comment]
I am also experiencing this issue now. I just updated all dependencies in my php project, but the issue does not change. I wonder whether the problem might be on SendGrid's side, and in that case, whether something can be done to 'handle the error'.

**Comment by JorisDebonnet** [comment]
I also started experiencing this issue recently. However, the issue went away for me after updating all my php dependencies with `composer update`. 

My alternative was going to be to use that StackOverflow's suggestion to send a HTTP 1.0 request instead of a HTTP 1.1 one, by editing `s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php:post()` (at the very end) to do this instead: 
```php
return $this->client->post($this->endpoint, $payload, ['version' => 1.0]);
```
